# Auto-generated by github-support-app for Docker 化
# Python 3.12-slim ベース、gunicorn で 0.0.0.0:8000 に bind。
# docker-compose.yml から ${WEB_PORT}:8000 として外部公開する。

FROM python:3.12-slim

# git は migrations / runtime で使うこともあるので入れておく
RUN apt-get update && apt-get install -y --no-install-recommends \
    git curl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 依存ライブラリ (gunicorn は外部依存に追加保証)
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt \
 && pip install --no-cache-dir gunicorn

# アプリのコード
COPY . .

# Flask の DB 初期化 / マイグレーションがエントリ起動時に走る前提。
# 別途必要なら docker-compose.yml の command: で先に流すこと。

EXPOSE 8000
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8000", "--access-logfile", "-", "wsgi:app"]
